Generate a self signed certificate when flight-www is installed
openflighthpc/openflight-omnibus-builder pull request #125
Opened 2021-05-26 13:06 UTC by WilliamMcCumstie

`HTTPs` is enabled implicitly when `flight-www` by generating a self signed certificate. The `domain` defaults to `hostname --fqdn`.

The `flight www cert-gen` command can be used to convert it into a `lets-encrypt` certificate.

2021-06-01 12:16 UTC, benarmston requested changes
I've pushed a commit changing the message slightly.  I've also added a couple of comments for you to look at.

2021-06-01 12:16 UTC, benarmston commented on builders/flight-www/package-scripts/flight-www/postinst
> +  domain=$(hostname --fqdn)
This exactly what I requested on the trello card.  I now realise that I meant `hostname -d`.  Can you change this please?

2021-06-01 12:16 UTC, benarmston commented on builders/flight-www/package-scripts/flight-www/postinst
> +  /opt/flight/bin/flight www enable-https >/dev/null 2>&1
There isn't any error handling here.  If either of these fail, the message below will still be displayed and mislead the user into believing that HTTPS has been enabled.  We need to only show the message below if HTTPS actually has been enabled.

2021-06-01 14:05 UTC, WilliamMcCumstie commented on builders/flight-www/package-scripts/flight-www/postinst
> +  /opt/flight/bin/flight www enable-https >/dev/null 2>&1
https://github.com/openflighthpc/openflight-omnibus-builder/pull/125/commits/409f1d01193212c9f4f930960194bf54c35bc73e

2021-06-01 14:05 UTC, WilliamMcCumstie commented on builders/flight-www/package-scripts/flight-www/postinst
> +  domain=$(hostname --fqdn)
https://github.com/openflighthpc/openflight-omnibus-builder/pull/125/commits/409f1d01193212c9f4f930960194bf54c35bc73e

2021-06-01 14:47 UTC, benarmston commented
@WilliamMcCumstie it looks like you force pushed away the change to the error message I'd made.  Can I get them back please?

2021-06-01 14:51 UTC, WilliamMcCumstie commented
Sorry wasn't quite finished, added the change back

2021-06-03 09:24 UTC, benarmston commented
I've adjusted the copy again.  It now looks good for `yum install flight-www`.  It didn't quite fit with the other copy when `yum install flight-web-suite`.  I've updated the web suite copy accordingly.

I'm going to put this on hold until web suite 2021.4 is released and then I'll rebase on that branch and double check the copy with `yum install flight-web-suite`.

I may also decide that `flight www cert-gen` output should include the domain that the cert was generated for.

2021-06-14 17:32 UTC, benarmston commented
I've rebased on latest `master`.  Not sure if the new version number is correct.  I'll reconsider that later.

2021-06-15 08:15 UTC, benarmston commented
@WilliamMcCumstie FYI I'm going to merge this to a new branch `user-web-suites-2021.5`.  Having all of the PRs related to the next user/web suite release on a single branch may make my release process a bit easier.

2021-06-15 08:15 UTC, merged

2021-06-15 12:41 UTC, WilliamMcCumstie commented
:+1: