Add a nginx location to download files
openflighthpc/openflight-omnibus-builder pull request #128
Opened 2021-05-27 18:05 UTC by WilliamMcCumstie

A new `/downloads` route has been added to `nginx` which serves file with `Content-Disposition: attachment`.

It also packages the landing page with support for `config-packs`. The files to be downloaded for each config pack should be stored as:
`/opt/flight/usr/share/www/config-packs/<pack-name>/<filename>`

The MIME type/`Content-Type` is inferred from the file extension. By default, `nginx` does not support `text/markdown`. Instead the `mime.type` file has been duplicated into `/opt/flight/etc/www` with the new entry markdown entry.

As the `/downloads` route is a new feature, the system versions have been bumped to `-system-1.1`. The packages still provide the old `-system-1.0` for backwards compatibility.

2021-05-28 13:01 UTC, benarmston commented on builders/flight-www/opt/flight/etc/www/mime.types
> +    text/css                                         cs;
`cs;` should be `css;`

2021-06-03 12:27 UTC, WilliamMcCumstie commented on builders/flight-www/opt/flight/etc/www/mime.types
> +    text/css                                         cs;
https://github.com/openflighthpc/openflight-omnibus-builder/pull/128/commits/bc0dedbd89602551b12e1a0cdc31389e13d3091b

2021-06-07 18:30 UTC, benarmston requested changes
Looking good. We can reduce the size of the mime type file that we ship; see comment below (above?).

2021-06-07 18:30 UTC, benarmston commented on builders/flight-headnode-landing-page/config/software/flight-headnode-landing-page.rb
> +  end
Nice way of setting that up.

2021-06-11 14:35 UTC, WilliamMcCumstie commented on builders/flight-headnode-landing-page/config/software/flight-headnode-landing-page.rb
> +  end
:+1:

2021-06-11 15:59 UTC, WilliamMcCumstie commented on builders/flight-www/dist/nginx.conf.tpl
> +    include /opt/flight/etc/www/mime.types;
d490936237064124b694b0acab708f63b81a308f

2021-06-15 08:58 UTC, benarmston commented
I've rebased to fix conflicts and changed the merge target to `user-web-suites-2021.5`.  LGTM.

2021-06-15 08:58 UTC, merged