Create a flight-python build-
openflighthpc/openflight-omnibus-builder pull request #130
Opened 2021-06-03 10:50 UTC by WilliamMcCumstie

Python version `3.8.10` has been packaged as `flight-python`.

The `flight-python-system-*` version has been repurposed to denote the `MAJOR.MINOR` release version. Because python packages are typically packaged with `penv`, they are coupled to a particular minor release. Using the system version is a shortcut for specifying these bounds.

The `flight-cert` package has been rebuilt to use `flight-python`.

2021-06-09 15:48 UTC, benarmston requested changes
I've added a commit that changes where the executables are installed.  I wanted to be able to add just the `flight-python` executables to `PATH`.

I've also attempted to package the symlinks in the RPM, with some success.  I'm somewhat concerned about leaving symlinks to executables when the RPM is removed.

I've also separated out the `flight-python` software definition from the `python` software definition.  This is in better keeping with how some of our other packages work and allows fiddling with `flight-python` without destroying the `python` build cache.

With those changes made, I've got a few questions for you.  I've added them inline below.

Also, the package doesn't build on either Centos8 or Ubuntu2004 (with or without my changes) can you take a look at those build errors too please?

2021-06-09 15:48 UTC, benarmston commented on builders/flight-certbot/config/software/enforce-flight-python.rb
> +  end
What's the purpose of this check?  I understand that we do this for `flight-runway` (i.e., ruby), but in that case we're using ruby (and bundler) as part of the build chain.  Are we using `python` as part of the build chain?  Is there some other reason for this?

2021-06-09 15:48 UTC, benarmston commented on builders/flight-certbot/config/software/flight-certbot.rb
> +  env['PATH'] = "/opt/flight/bin:#{env['PATH']}"
I needed the `python` from `flight-python` to fix an issue with `flight env create easybuild`.  I decided there that adding `/opt/flight/bin/` to the path brought in too much.  I've added a commit so that we have

* `/opt/flight/opt/python/bin/{python,python3,pip,pip3}`
* `/opt/flight/bin/{python,python3,pip,pip3}`

This should be updated to add `/opt/flight/opt/python/bin/`.

2021-06-09 15:48 UTC, benarmston commented on builders/flight-python/config/projects/flight-python.rb
> +end
If you know of a better workaround than this I'd love to hear it.

Currently, the build machine has regular files at `/opt/flight/opt/python/bin/{python3,pip3}` and symlinks at `/opt/flight/opt/python/bin/{python,pip}` and `/opt/flight/bin/{python3,pip3,python,pip}`.

The RPM gets regular files at `/opt/flight/opt/python/bin/{python3,pip3}`  and `/opt/flight/bin/{python3,pip3,python,pip}` and symlinks at `/opt/flight/opt/python/bin/{python,pip}`.

2021-06-09 15:48 UTC, benarmston commented on builders/flight-python/config/software/flight-python.rb
> +  end
What are we trying to prevent here?

2021-06-09 15:48 UTC, benarmston commented on builders/flight-python/config/software/python.rb
> +name 'python'
Is there a reason that you didn't reuse the software definition at `share/python3`?

2021-06-09 15:48 UTC, benarmston commented on builders/flight-python/config/software/readline.rb
> +name "readline"
Is there a reason that you didn't reuse the software definition at `share/readline`?

2021-06-09 15:48 UTC, benarmston commented on builders/flight-python/config/software/sqlite.rb
> +name 'sqlite'
Is there a reason that you didn't reuse the software definition at `share/sqlite`?

2021-06-09 15:48 UTC, benarmston commented on builders/flight-python/dist/bin/pip3
> +_setup
I can't decide if I think this is correct or not.  I'm not sure that we want to write our own tools in `python`, but we do want to be able to rely on `python` for our tool's dependencies.  Did you have something particular in mind when you added this `_setup`?

2021-06-10 10:01 UTC, WilliamMcCumstie commented on builders/flight-python/config/software/flight-python.rb
> +  end
You can't build `flight-python` if an existing version is installed within `/opt/flight/opt/python`. Doing so can create conflicts between the newly built files and the installed `rpm`.

2021-06-10 10:03 UTC, WilliamMcCumstie commented on builders/flight-python/config/software/python.rb
> +name 'python'
Mainly because I forgot about the shared version.

However moving forward we won't need the `share/python3` as we can specify a `runtime_dependency: flight-python`. It can be removed once all the relevant package builders have been updated.

2021-06-10 10:03 UTC, WilliamMcCumstie commented on builders/flight-python/config/software/readline.rb
> +name "readline"
Ditto,

However we can probably use the shared version.

2021-06-10 10:04 UTC, WilliamMcCumstie commented on builders/flight-python/config/software/sqlite.rb
> +name 'sqlite'
Ditto,

However I don't think anything uses `sqlite` apart from `python`. So the shared version *may* be removed once the packages are ported.

2021-06-10 10:07 UTC, WilliamMcCumstie commented on builders/flight-python/dist/bin/pip3
> +_setup
I'm not  exactly sure what you are referring to.

I cargo programmed this from `/o/f/b/yarn`:

```
_setup() {
  local a xdg_config
  IFS=: read -a xdg_config <<< "${XDG_CONFIG_HOME:-$HOME/.config}:${XDG_CONFIG_DIRS:-/etc/xdg}"
  for a in "${xdg_config[@]}"; do
    if [ -e "${a}"/flight.rc ]; then
      source "${a}"/flight.rc
      break
    fi
  done
  if [ -d "${flight_ROOT}"/libexec/hooks ]; then
    shopt -s nullglob
    for a in "${flight_ROOT}"/libexec/hooks/*.sh; do
      source "${a}"
    done
    shopt -u nullglob
  fi
}

flight_ROOT=${flight_ROOT:-$(cd $(dirname ${BASH_SOURCE[0]})/.. && pwd)}
_setup
unset _setup

exec ${flight_ROOT}/bin/node \
     ${flight_ROOT}/opt/nodejs/bin/yarn.js "$@"

```

2021-06-10 10:10 UTC, WilliamMcCumstie commented on builders/flight-certbot/config/software/enforce-flight-python.rb
> +  end
A few packages require `pip` as part of the build (e.g. `flight-certbot`). The builds are dependent on the `MAJOR.MINOR` version of `python`.

2021-06-10 10:44 UTC, benarmston commented on builders/flight-python/config/software/flight-python.rb
> +  end
This also catches the case that `flight-python` has simply been built previously, which is very annoying.  Perhaps I introduced that with my changes to where the binaries are being installed.  If so, that might be relatively simple to undo.

Do you recall if this check caused problems with rebuilds previously?

2021-06-10 10:44 UTC, benarmston commented on builders/flight-python/config/software/python.rb
> +name 'python'
In that case.  There are some differences between the two software definitions.  Can you take a look and convince yourself (and me) that we want those differences.

2021-06-10 10:44 UTC, benarmston commented on builders/flight-python/config/software/readline.rb
> +name "readline"
Using the shared version sounds good.  Again there are differences.  Just the version number.

2021-06-10 10:44 UTC, benarmston commented on builders/flight-python/config/software/sqlite.rb
> +name 'sqlite'
Big differences between the two this time.  Can you take a look at them and convince yourself (and me) that we want those differences.

2021-06-10 10:45 UTC, benarmston commented on builders/flight-python/dist/bin/pip3
> +_setup
It's correct for `node`, because we have APIs written in JavaScript that we want to start in the correct environment.  I guess we have some tools written in python already `certbot` and `directory`.  With `certbot`, we always use it via a wrapper, `flight www cert-gen`, and that wrapper sets up the flight environment.  I'm not sure what we do with directory.

That's mostly thinking out loud.

This is fine.  Let's keep it.

2021-06-10 10:46 UTC, benarmston commented on builders/flight-certbot/config/software/enforce-flight-python.rb
> +  end
Fair enough.  Sounds like something we should be doing then.

2021-06-10 11:21 UTC, WilliamMcCumstie commented on builders/flight-python/config/software/flight-python.rb
> +  end
Hmm it shouldn't be picking up old builds?

The `/o/f/bin/python` files are `extra_package_files`, IIRC these should only be present when installing the `rpm`. I may be wrong, but this should not happen at build time.

There maybe something funky happening with symlinks?

2021-06-10 13:16 UTC, benarmston commented on builders/flight-python/config/software/flight-python.rb
> +  end
It's likely a hold over from my attempt to make `/o/f/b/python` et al symlnks.  https://github.com/openflighthpc/openflight-omnibus-builder/pull/130/commits/7236eed068585e6bc803e75f1e0baabcef88fe46#diff-092b957480f07bb0a69e66d1054fb0f94d70fed2ca3c4be2461fa6fb244cedc1R23.  The block of code there creates symlinks on the build machine at `/opt/flight/bin/python` et al.  As symlink packaging isn't working correctly, perhaps changing that to copy `dist/bin/*` to `opt/flight/bin/` is the better solution.

2021-06-10 15:34 UTC, benarmston commented on builders/flight-python/config/software/flight-python.rb
> +  end
It no longer fails on reinstall. I decided on abandoning symlinks though.

2021-06-10 15:36 UTC, benarmston commented on builders/flight-python/config/software/flight-python.rb
> +  end
> You can't build `flight-python` if an existing version is installed within `/opt/flight/opt/python`. Doing so can create conflicts between the newly built files and the installed `rpm`.

What kind of conflicts are you referring to here?

2021-06-11 13:54 UTC, WilliamMcCumstie commented on builders/flight-python/config/software/flight-python.rb
> +  end
Every file within `/opt/flight/opt/python` creates a conflict. We build all packages in place (directly within `/opt/flight/opt/<app>`) so that anything that hard codes a path will be correct.

This isn't an issue for the majority of builds (e.g, `flight-job`) as it will not be installed on the `builder`. This means `/opt/flight/opt/job` will be an empty directory ready for the build. It also means it is safe to run `rm -rf` or `omnibus clean --purge` over the directory before building.

The same does not apply `flight-python` as it is required to build other packages (e.g. `flight-cerbot`). This means `/opt/flight/opt/python` may not be empty and `rm -rf`/ `omnibus clean --purge` are now dangerous operations.

---

This is why I have added a check to ensure `flight-python` is not installed before building `flight-python`. Technically `flight-runway` (maybe `flight-nodejs`?) is susceptible to the same issue. However these have legacy builders before all the idiosyncrasies where identified.

2021-06-11 14:10 UTC, WilliamMcCumstie commented on builders/flight-python/config/software/python.rb
> +name 'python'
So the `env` handling is a little bit different, I think this is primarily due to cargo programming from `omnibus-software` upstream definitions.

There seems to be the "standard" methods `with_standard_compiler_flags(with_embedded_path())` that sets the compiler flags vs. setting them manually. AFAICS there is no particularly advantage of one over the other.

I am partially to using the standard methods, mainly because its a bit more verbose in what it sets.

---

Apart from that, there where a couple of missing dependencies. I have added `gdbm` back, which should fix your build issues on ubuntu.

I've also added `bzip2` back, but I don't think it's actually being used.

2021-06-11 14:24 UTC, WilliamMcCumstie commented on builders/flight-python/config/software/readline.rb
> +name "readline"
So there are a couple of difference:

The license in the original file looks wrong. `SQLITE` uses a "blessing" that puts it in the open domain. The original `libxslt` license looks wrong.

A latter version of `sqlite` is being built, `3.35.5` vs `3.31.1`. Don't see this causing an issue, it will almost certainly be compatible. We should probably look to build with the latter version.

The `relative_path` is a bit different, but this is a non-issue. It gives the name of the directory after the tarball is extracted. Don't know why it is different, possible due to a latter version? As long as the package builds, it is fine.

We aren't using the `--disable-readline` flag in the build. We are building it with `readline`, so no point disabling it.

Finally we are using the standard `env = with_standard_compiler_flags(with_embedded_path())` instead of the custom configuration. Generally I am partially to this method for consistency.

---

tl;dr There are a few difference, but they shouldn't be an issue.

2021-06-11 14:32 UTC, WilliamMcCumstie commented on builders/flight-python/config/software/sqlite.rb
> +name 'sqlite'
So there are a couple of difference:

The license in the original file looks wrong. `SQLite` uses a "blessing" that puts it in the public domain. The original `libxslt` license looks wrong.

A latter version of `sqlite` is being built, `3.35.5` vs `3.31.1`. Don't see this causing an issue, it will almost certainly be compatible. We should probably look to build with the latter version.

The `relative_path` is a bit different, but this is a non-issue. It gives the name of the directory after the tarball is extracted. Don't know why it is different, possible due to a latter version? As long as the package builds, it is fine.

~We aren't using the `--disable-readline` flag in the build. We are building it with `readline`, so no point disabling it.~

Finally we are using the standard `env = with_standard_compiler_flags(with_embedded_path())` instead of the custom configuration. Generally I am partially to this method for consistency.

---

tl;dr There are a few difference, but they shouldn't be an issue.

2021-06-11 14:33 UTC, WilliamMcCumstie commented on builders/flight-python/config/software/readline.rb
> +name "readline"
Removed

2021-06-11 14:33 UTC, WilliamMcCumstie commented on builders/flight-python/config/software/sqlite.rb
> +name 'sqlite'
Nope: We need `--disabled-readline` because `sqlite` uses a different version on `centos8`

2021-06-11 14:33 UTC, WilliamMcCumstie commented on builders/flight-python/dist/bin/pip3
> +_setup
:+1:

2021-06-15 08:19 UTC, benarmston commented on builders/flight-certbot/config/software/flight-certbot.rb
> +  env['PATH'] = "/opt/flight/bin:#{env['PATH']}"
@WilliamMcCumstie can we get this updated please.

2021-06-15 08:35 UTC, benarmston commented on builders/flight-python/config/software/flight-python.rb
> +  end
I'm still not sure what you mean by conflict.  RPMs can conflict with each other in a couple of ways.  The RPM itself can be flagged to `Conflicts: other-rpm`; or an RPM can own a file that is also owned by another RPM.  We have neither of those situations here.

The installed `flight-python` RPM is the same RPM as the one being built, albeit a different version.  An RPM can't `Conflicts` with itself, even a later version.  A file ownership conflict cannot exist between two different versions of an RPM.

I'm left confused as to what kind of conflict you are referring to.

I understand that `yum install flight-python` will result in files being placed into `/opt/flight/bin/` and `/opt/flight/opt/python`.  I also understand that some of those files may be overwritten when running `omnibus build flight-python`.

What I don't understand is what issue that is going to cause.

I don't understand why `omnibus clean --purge` is "dangerous".  I can see that it could break an installation of the `flight-python` RPM package.  But that is easily recoverable, by reinstalling the RPM.

This mechanism also recovers from the issue of some files being overwritten when running `omnibus build flight-python`.

---

Regarding `flight-runway` and `flight-nodejs`, it may be that they also suffer from this issue and should be updated.  But before I can make a decision on that I need to understand what this issue is.

2021-06-15 08:43 UTC, benarmston commented on builders/flight-python/config/software/sqlite.rb
> +name 'sqlite'
Does `env = with_standard_compiler_flags(with_embedded_path())` produce the same environment as is set manually?

This should be renamed to `sqlite3`.  I don't think it is a good idea to introduce arbitrary naming variations from upstream, and I can't see a reason why we'd want to deviate from the name selected by upstream.

2021-06-15 08:49 UTC, benarmston commented on builders/flight-python/config/software/python.rb
> +  #        or you can specify "--disable-ipv6".
Is this comment still relevant?  Are we compiling python with `zlib` and `openssl`?

2021-06-15 12:57 UTC, WilliamMcCumstie commented on builders/flight-python/config/software/flight-python.rb
> +  end
I think we are using two different meanings of the word "conflict". I mean it in a generic sense when two files try and write to the same location.

> The RPM itself can be flagged to `Conflicts: other-rpm`; or an RPM can own a file that is also owned by another RPM. We have neither of those situations here.

I'm not referring to multiple `rpms` conflicting with each other. I am referring to the `builder` conflicting with an `rpm`. As `yum` is not involved in this, the `Conflict:` flag does not work.

> The installed flight-python RPM is the same RPM as the one being built, albeit a different version

That's almost always not true as they will be different versions. Best case scenario they will have the same filenames but updated versions. In this case, all the old versions _should_ be replaced (hopefully, maybe?). However there are multiple pit falls including but not limited to:

* We don't know how `make install` works, it may not replace the file, and
* If the filenames change, the old stale versions will be included in the new `rpm`.

Overall, there are too many *shoulds* and *maybes* for my liking. We definitely want to be building from a clean slate hence the check.

> I don't understand why `omnibus clean --purge` is "dangerous". I can see that it could break an installation of the flight-python RPM package. But that is easily recoverable, by reinstalling the RPM.

Yes this is technically true, but I would always classify breaking a system install as "dangerous". We should avoid doing so if possible.

2021-06-15 13:12 UTC, WilliamMcCumstie commented on builders/flight-python/config/software/flight-python.rb
> +  end
> This mechanism also recovers from the issue of some files being overwritten when running omnibus build flight-python.

It doesn't recover if the filenames have changed. This can occur quite frequently as `python3` hard codes the `MAJOR.MINOR` release into some of its paths:

```
$ ls  /opt/flight/opt/python/embedded/include/python3.8/
abstract.h         cpython                import.h               odictobject.h      pyhash.h       setobject.h
asdl.h             datetime.h             internal               opcode.h           pylifecycle.h  sliceobject.h
ast.h              descrobject.h          interpreteridobject.h  osdefs.h           pymacconfig.h  structmember.h
bitset.h           dictobject.h           intrcheck.h            osmodule.h         pymacro.h      structseq.h
bltinmodule.h      dtoa.h                 iterobject.h           parsetok.h         pymath.h       symtable.h
boolobject.h       dynamic_annotations.h  listobject.h           patchlevel.h       pymem.h        sysmodule.h
bytearrayobject.h  enumobject.h           longintrepr.h          picklebufobject.h  pyport.h       token.h
bytes_methods.h    errcode.h              longobject.h           pyarena.h          pystate.h      traceback.h
bytesobject.h      eval.h                 marshal.h              pycapsule.h        pystrcmp.h     tracemalloc.h
cellobject.h       fileobject.h           memoryobject.h         pyconfig.h         pystrhex.h     tupleobject.h
ceval.h            fileutils.h            methodobject.h         pyctype.h          pystrtod.h     typeslots.h
classobject.h      floatobject.h          modsupport.h           py_curses.h        Python-ast.h   ucnhash.h
codecs.h           frameobject.h          moduleobject.h         pydebug.h          Python.h       unicodeobject.h
code.h             funcobject.h           namespaceobject.h      pydtrace.h         pythonrun.h    warnings.h
compile.h          genobject.h            node.h                 pyerrors.h         pythread.h     weakrefobject.h
complexobject.h    graminit.h             object.h               pyexpat.h          pytime.h
context.h          grammar.h              objimpl.h              pyfpe.h            rangeobject
```

2021-06-15 13:25 UTC, WilliamMcCumstie commented on builders/flight-python/config/software/sqlite.rb
> +name 'sqlite'
Renamed: https://github.com/openflighthpc/openflight-omnibus-builder/pull/130/commits/d4b7861806c761dfaf7b1e9c4bafc44b72e7c145

2021-06-15 13:27 UTC, WilliamMcCumstie commented on builders/flight-python/config/software/python.rb
> +  #        or you can specify "--disable-ipv6".
Yep that is still relevant

We are compiling with `zlib` and `openssl` but only because `zlib-devel` and `openssl-devel` is installed on the system.

`python3` does not appear to have options to force the compiler to include the libraries or error.

2021-06-15 13:55 UTC, WilliamMcCumstie commented on builders/flight-python/config/software/sqlite.rb
> +name 'sqlite'
So the standard flags are the following:

```
CFLAGS="-I/opt/flight/opt/python/embedded/include -O2 -D_FORTIFY_SOURCE=2 -fstack-protector"
CPPFLAGS="-I/opt/flight/opt/python/embedded/include -O2 -D_FORTIFY_SOURCE=2 -fstack-protector"
CXXFLAGS="-I/opt/flight/opt/python/embedded/include -O2 -D_FORTIFY_SOURCE=2 -fstack-protector"
LDFLAGS="-Wl,-rpath,/opt/flight/opt/python/embedded/lib -L/opt/flight/opt/python/embedded/lib"
LD_RUN_PATH="/opt/flight/opt/python/embedded/lib"          
OMNIBUS_INSTALL_DIR="/opt/flight/opt/python"               
PATH="/opt/flight/opt/python/bin:/opt/flight/opt/python/embedded/bin:/home/vagrant/openflight-omnibus-builder/vendor/ruby/2.7.0/bin:/usr/local/rvm/gems/ruby-2.7.2/bin:/usr/local/
rvm/gems/ruby-2.7.2@global/bin:/usr/local/rvm/rubies/ruby-2.7.2/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/usr/local/rvm/bin:/home/vagrant/.local/bin:/home/vagrant/bin"
PKG_CONFIG_PATH="/opt/flight/opt/python/embedded/lib/pkgconfig"
```

Obviously there are additional environment variables (mostly concerning `c++`). These will be ignored by `gcc`, and there is already precedence for doing this. 

The three original env vars where:

```
"LDFLAGS" => "-Wl,-rpath,#{install_dir}/embedded/lib -L#{install_dir}/embedded/lib -I#{install_dir}/embedded/include",
"CFLAGS" => "-L#{install_dir}/embedded/lib -I#{install_dir}/embedded/include",
"LD_RUN_PATH" => "#{install_dir}/embedded/lib"
```

Of which, `LD_RUN_PATH` is the same.

The `CFLAGS` and `LDFLAGS` have a minor difference. It looks like the original version of `CFLAGS` includes a `-L` directive to the linker and `LDFLAGS` a `-I` directive to the compiler. This doesn't really make sense, my guess the flags where duplicated at some point. I am comfortable that `with_standard_env` omits the duplicate directives where appropriate.

Otherwise the `with_standard_env` has the following additional options:

* `-fstack-protector`: Additional protections against buffer overflows,
* `-D_FORTIFY_SOURCED=2`: Run additional compiler time checks on some `libc` functions (when supported),
* `-O2`: Apply a bunch of compiler optimisations

Overall `with_standard_env` looks to be what we want

2021-06-15 14:46 UTC, WilliamMcCumstie commented on builders/flight-certbot/config/software/flight-certbot.rb
> +  env['PATH'] = "/opt/flight/bin:#{env['PATH']}"
So we don't need both on this `PATH`; one or the other is sufficient. I've gone with the internal `/opt/flight/opt/python/bin`.

However the original shims where broken as they directly `cp` the distro versions. This meant `flight_ROOT` was being set to `/opt/flight/opt/python` and breaks everything.

Instead I've updated the shims to use an `exec`.

2021-06-15 14:46 UTC, WilliamMcCumstie commented on builders/flight-certbot/config/software/flight-certbot.rb
> +  env['PATH'] = "/opt/flight/bin:#{env['PATH']}"
36f8b33afde87cd8fe47d7b028ba904a02c48a29

2021-06-15 15:05 UTC, WilliamMcCumstie commented on builders/flight-certbot/config/software/flight-certbot.rb
> +  env['PATH'] = "/opt/flight/bin:#{env['PATH']}"
Changed my mind, I got `symlinks` working in `/opt/flight/opt/python/bin`:

https://github.com/openflighthpc/openflight-omnibus-builder/pull/130/commits/a8b9b914ff401191af033be3ea721aa6c0ae58d4

2021-06-15 15:06 UTC, WilliamMcCumstie commented on builders/flight-python/config/projects/flight-python.rb
> +end
The trick is to create the symlinks within `/opt/flight/opt/python/bin` within the software file. This way `omnibus` will handle the symlink natively.

https://github.com/openflighthpc/openflight-omnibus-builder/pull/130/commits/a8b9b914ff401191af033be3ea721aa6c0ae58d4

2021-06-15 15:17 UTC, WilliamMcCumstie commented on builders/flight-python/config/projects/flight-python.rb
> +end
As far as `/opt/flight/bin` goes, they have to be regular files

2021-06-16 09:10 UTC, benarmston commented on builders/flight-certbot/config/software/flight-certbot.rb
> +  env['PATH'] = "/opt/flight/bin:#{env['PATH']}"
> So we don't need both on this `PATH`; one or the other is sufficient. I've gone with the internal `/opt/flight/opt/python/bin`.

Good.  That's what I asked for :-)

2021-06-16 09:27 UTC, benarmston commented on builders/flight-python/config/software/flight-python.rb
> +  end
> I think we are using two different meanings of the word "conflict". I mean it in a generic sense when two files try and write to the same location.

I had been trying to avoid using "conflict" for exactly this reason; it isn't well-defined in this scenario.  Hence my requests for you to define it.

I think I now understand your concerns.

1. When building an RPM, the contents of `/opt/flight/opt/<NAME>` and some of the contents of `/opt/flight/{bin,libexec,...}` are included in the built RPM.
2. We want to ensure that artefacts of previous builds are not included in the newly built RPM.
3. For many of our builders we do not expect any of the built RPMs to be installed on the build machine. So we can achieve (2) by running `clean --purge`.
4. For some of our builders we do expect the built RPM to be installed on the build machine.  Running `clean --purge` will remove files belonging to that installed RPM.  Running `build` will overwrite/replace files belonging to that installed RPM.  This can result in an unpredictable mix of files belonging to the installed RPM and/or the newly built RPM.
5. Using that unpredicatble mix to build additional packages is likely to have unpredictable and undesirable outcomes.

Could you clarify that I've understood you correctly.

The above certainly seems like a valid concern.

2021-06-16 09:35 UTC, benarmston commented on builders/flight-python/config/software/sqlite.rb
> +name 'sqlite'
Yep.  Those look fine to me.  Thanks for checking that.

2021-06-16 09:44 UTC, benarmston commented on builders/flight-certbot/config/software/flight-certbot.rb
> +  env['PATH'] = "/opt/flight/bin:#{env['PATH']}"
Regarding the symlinks.  Good catch on the `flight_ROOT` setup issue.

However, we now have `/opt/flight/bin/python` and `/opt/flight/opt/python/bin/python` behaving differently.  The first performs the standard flight setup routines and the latter does not.  I wonder if this is going to surprise us later.  Did you consider this difference when you made the change?

2021-06-16 10:12 UTC, benarmston commented on builders/flight-python/config/software/python.rb
> +  #        or you can specify "--disable-ipv6".
That does seem very annoying.  I can't find a way to get that to work (fail) as it should either.

2021-06-16 10:24 UTC, WilliamMcCumstie commented on builders/flight-python/config/software/python.rb
> +  #        or you can specify "--disable-ipv6".
¯\_(ツ)_/¯

2021-06-16 10:32 UTC, WilliamMcCumstie commented on builders/flight-python/config/software/flight-python.rb
> +  end
> I had been trying to avoid using "conflict" for exactly this reason; it isn't well-defined in this scenario. Hence my requests for you to define it.

Fair point, `conflict` does have a narrowly defined meaning within the context of the builder. Will try and avoid using it in the future.

> Could you clarify that I've understood you correctly

That sums it up quite nicely :+1:

2021-06-16 10:47 UTC, WilliamMcCumstie commented on builders/flight-certbot/config/software/flight-certbot.rb
> +  env['PATH'] = "/opt/flight/bin:#{env['PATH']}"
Yep I noticed that. I first tried symlinking `/o/f/o/python/bin` to `/o/f/bin` however it broke due to the before mentioned `flight_ROOT` issue. Turns out `BASH_SOURCE` reverse-follows symlinks, TIL.

So the alternative is using `exec`:

1. `/o/f/o/python/bin` first `exec` into `/o/f/bin`,
2. `/of/o/bin` does the regular setup and `exec` into `/o/f/o/python/embedded/bin`

I found this to be counter intuitive as well, so was left with a choice:

1. Jump in and out of `/o/f/o/python` and get the special handling provided by `/o/f/bin`, OR
2. Stay within `/o/f/o/python` and forego the special handling.

---

So the question comes down to: _do we need the special handling?_

AFAICS the special handling does three things:

* Applies "flight" related env vars from a `flight.rc`,
* Applies a bunch of hooks, and
* Ensure `flight_ROOT` is set.

I can't think of any "flight env vars" which will be particularly important for `python` (barring `flight_ROOT`), so the `flight.rc` is probably irrelevant. The same applies to the hooks.

However changing the `flight_ROOT` would make `/of/o/python/bin` execute something other than `/o/f/o/python/embedded/bin`. This would be highly surprising and should be avoided.

---

tl;dr It is probably fine as it, both methods have draw backs.

If you want the standard behaviour use `/o/f/bin`. If you want to guarantee the python you use, select `/o/f/o/python/bin`.

2021-06-16 11:01 UTC, benarmston commented on builders/flight-python/config/software/flight-python.rb
> +  end
:+1: 

The mechanism implemented seems like a reasonable way of detecting and avoiding this.

2021-06-17 10:43 UTC, benarmston commented on builders/flight-certbot/config/software/flight-certbot.rb
> +  env['PATH'] = "/opt/flight/bin:#{env['PATH']}"
I'm not sure if this is the behaviour we want or not.  It is at least consistent with how `flight-nodejs` does things and that seems to work.  If it turns out to be wrong, we'll find out and fix it then.

2021-06-17 10:48 UTC, benarmston commented on builders/flight-python/config/software/python.rb
> +name 'python'
These are similar enough that its probably fine.

2021-06-17 10:53 UTC, benarmston commented
Thanks for your work on this @WilliamMcCumstie.  LGTM.

2021-06-17 10:53 UTC, merged