Restart/stop the services on upgrade and removal
openflighthpc/openflight-omnibus-builder pull request #134
Opened 2021-06-11 11:12 UTC by WilliamMcCumstie

The `flight-web-suite` packages are now `restarted` on `upgrade` and `stopped` on `removal`.

This is done using the `package-scripts`:

* `postinst`: Checks if the service was already running and `restarts` when required,
* `prerm`: Stops the service on full removal, and
* `postrm`: Reloads the `nginx` config.

The `prerm` script is required because `flight-service` can not stop a service it does not know about. This means the services need to be stopped before uninstalling them. This only runs when the package is being removed as opposed to upgraded.

Both the `postinst` and `postrm` scripts need to reload the `nginx` configs. On `upgrade`, `yum` sometimes (always?) runs the `postinst` of the new package before completely removing the older package. This leads to the wrong `nginx` configurations being reloaded. Reloading the `nginx` config in `postrm` fixes this.

---

Broadly the `postinst`/`prerm`/`postrm` scripts are the same for all the `web-suite` packages. A new `update_web_suite_package_scripts.rb` shared software config has been added to manage these files. It is broadly based on `update_puma_scripts.rb`.

The major differences between the difference services are within the `postinst` scripts. It is fairly common to run some form of "configuration" before starting the service. To handle this, a new `postinst-configure` script can be optionally rendered into `postinst`. All custom configuration should be preformed within `postinst-configure` and the build will automatically update `postinst`.

2021-06-16 10:15 UTC, benarmston requested changes
I've made my first pass through this.  I've not yet built or tested the packages, so more comments may be added when I do.

In addition to the comments below: why have the permissions on the `service/types/*/*` scripts changed?  `flight-service` executes those files as `bash /path/to/file` so they don't need to be executable.

2021-06-16 11:59 UTC, WilliamMcCumstie commented on builders/flight-job-script-api/opt/flight/etc/service/types/job-script-api/start.sh
> +tool_bg /opt/flight/opt/job-script-api/bin/start "$pidfile"
The `puma` service files now managed by a shared `update_puma_scripts`. So the short answer is: _to be consistent with the other `puma` scripts_.

As to why `/opt/flight` is hard coded in general, this is a bit more complicated. 

---

Firstly `flight_ROOT` does not always work everywhere as it won't be defined. In particular: `package-scripts` (e.g. `postinst`), crontabs, and `flight-service` env files.

They would either have to source a file within `/o/f/b` negating the point of `flight_ROOT`. Or use `XDG` which is another can of worms.

This doesn't *technically* apply to the `puma` scripts. However we are currently relying on memory for when it does and does not work.

---

Secondly, using `flight_ROOT` does not add portability in this situation. These scripts are rendered dynamically `update_puma_scripts`. Changing the `/opt/flight` prefix (within the script) would be a reasonable trivial tasks.

There are a few details that would need addressing, nothing consequential:
* The mechanism doesn't currently exist,
* The relative paths within `builders/<app>/opt/flight` would be wrong and
* The files are checked into the repo.

We haven't had a need to move the builds (_yet_), so I've kicked that can down the road. Updating the `puma` scripts would be the least of the concerns.

---

By the time you are running the `start.sh` script, `flight_ROOT` has already been set. This is because it is buried within the `/opt/flight` tree:

`/opt/flight/etc/service/types/job-script-api/start.sh`

It's also extremely difficult to run the `start.sh` script manually due to the special `flight-service` methods (e.g. `tool_bg`). This means there is no use case for the following:

```
# Somehow get tool_bg define
flight_ROOT=/some/where/else /opt/flight/etc/service/types/job-script-api/start.sh
```

I do however expect the following script to start the version the `embedded` version of the code:

```
# This should start the version within /o/f/o/<app>
/opt/flight/opt/<puma-app>/bin/start
```

---

There is also precedence for hard coding the paths within the rpms:

```
[vagrant@chead1 ~]$ cat /opt/flight/opt/service/vendor/ruby/2.7.0/gems/ffi-1.11.1/lib/ffi_c.so  | grep '/opt/flight'
Binary file (standard input) matches
[vagrant@chead1 ~]$ cat /opt/flight/opt/runway/embedded/lib/libruby.so | grep "/opt/flight"
Binary file (standard input) matches
```

This a new `/opt/flight` couldn't be created with a simple `cp`. Instead a new build would be required.

---

TL;DR;

1. We are relying on `memory` for when `flight_ROOT` does and does not work,
2. Hard coding improves consistency and readability to the scripts,
3. There is precedence for hard coding `/opt/flight` (within the builder), and
4. Updating the `puma` script at build time is fairly trivial.

PS: This only applies to files checked into the builder repo. External packages definitely should use `flight_ROOT`.

2021-06-16 13:04 UTC, WilliamMcCumstie commented on builders/flight-desktop-restapi/config/projects/flight-desktop-restapi.rb
>    runtime_dependency 'flight-action-api (>= 1.4.0)'
On review, `flight-desktop-restapi` does not have any configuration options, so `flight service configure --force` is a moot point.

Removed the dep: baa9e8c8c976cce34cb90a3c8d85bffca40674e9

2021-06-16 13:11 UTC, WilliamMcCumstie commented on builders/flight-desktop-restapi/config/projects/flight-desktop-restapi.rb
>    runtime_dependency 'flight-action-api (>= 1.4.0)'
Oh you are talking about the `flight-action-api`! Didn't even see it

This a pre-existing issue since: 68cbf98a

Fixed: 2edb4cd2ac825d6d67de80a06a1e62037dbd93b5

2021-06-16 13:13 UTC, WilliamMcCumstie commented on builders/flight-www/package-scripts/flight-www/postinst
> +/opt/flight/bin/flight service reload www >/dev/null 2>&1
https://github.com/openflighthpc/openflight-omnibus-builder/pull/134/commits/398ba653214bbf54a9472bf6e8613f7025b4bb0a

2021-06-16 13:14 UTC, WilliamMcCumstie commented on builders/flight-www/package-scripts/flight-www/postinst
> +/opt/flight/bin/flight service reload www >/dev/null 2>&1
https://github.com/openflighthpc/openflight-omnibus-builder/pull/134/commits/258d9bad4d79608c6214fcd7bbdc6215c724dc97

2021-06-17 14:04 UTC, benarmston commented on builders/flight-desktop-restapi/config/projects/flight-desktop-restapi.rb
>    runtime_dependency 'flight-action-api (>= 1.4.0)'
:+1:

2021-06-17 14:12 UTC, benarmston commented on builders/flight-www/package-scripts/flight-www/postinst
> +/opt/flight/bin/flight service reload www >/dev/null 2>&1
:+1:

2021-06-17 14:22 UTC, benarmston commented on builders/flight-job-script-api/opt/flight/etc/service/types/job-script-api/start.sh
> +tool_bg /opt/flight/opt/job-script-api/bin/start "$pidfile"
You're right that we can't always rely on `flight_ROOT` being set.  But rather than introducing additional hard coding of `/opt/flight` we should use `${flight_ROOT:-/opt/flight}`.

We may never need to relocate where we install our packages, but we shouldn't be making it harder for us to do so if we ever need it.

2021-06-22 10:37 UTC, WilliamMcCumstie commented
Rebased to remove rogue `.env` file

2021-06-22 12:48 UTC, WilliamMcCumstie commented on builders/flight-job-script-api/opt/flight/etc/service/types/job-script-api/start.sh
> +tool_bg /opt/flight/opt/job-script-api/bin/start "$pidfile"
I've reworked the `puma` scripts to use `flight_ROOT` whether possible. I have avoided using `${flight_ROOT:-/opt/flight}` in fair of exiting with an error. I've done this for two reasons:

1. There is already precedence in favour of an error, and
2. `flight_ROOT` should already be set by `flight-service`, if not, its an error condition.

---

This package scripts are a little bit different. I am fairly certain that `rpm` and `deb` run the scripts in a "clean" environment. This means `flight_ROOT` "should" always be unset.

Using the conditional assignment (`${flight_ROOT:-/opt/flight}`) would apply otherwise, and lead to confusion. Instead I have hard set `flight_ROOT=/opt/flight` at the top of the scripts.

This has two advantages:

* It makes it clear what `flight_ROOT` is within the package scripts, and
* It will be fairly easy to change at a future point if need be

2021-06-24 15:42 UTC, benarmston requested changes

2021-06-24 15:42 UTC, benarmston commented on builders/flight-console-api/package-scripts/flight-console-api/postinst
> +${flight_ROOT}/bin/flight service configure --force >/dev/null 2>&1
Looks like this is missing a service name.

Also, my initial testing shows that `--config '{}'` is needed.

```
[vagrant@chead1 (dev) flight-job]$ ${flight_ROOT}/bin/flight service configure www --force  | cat
flight service: Cannot continue within a non-interactive terminal!
Please specify the configs with the following flag: --config JSON
[vagrant@chead1 (dev) flight-job]$ ${flight_ROOT}/bin/flight service configure www --force --config '{}'  | cat
Changes applied.
```

2021-06-24 15:42 UTC, benarmston commented on builders/flight-console-api/package-scripts/flight-console-api/postinst-configure
> +${flight_ROOT}/bin/flight service configure --force >/dev/null 2>&1
Above comments apply here.

2021-06-24 15:42 UTC, benarmston commented on builders/flight-desktop-restapi/package-scripts/flight-desktop-restapi/postinst
> +${flight_ROOT}/bin/flight service configure --force desktop-restapi >/dev/null 2>&1
I think `--config '{}'` is needed here.

2021-06-24 15:42 UTC, benarmston commented on builders/flight-file-manager-api/package-scripts/flight-file-manager-api/postinst
> +${flight_ROOT}/bin/flight service configure --force file-manager-api >/dev/null 2>&1
I think `--config '{}'` is needed here.

2021-06-24 15:42 UTC, benarmston commented on builders/flight-file-manager-api/package-scripts/flight-file-manager-api/postinst-configure
> +${flight_ROOT}/bin/flight service configure --force file-manager-api >/dev/null 2>&1
I think `--config '{}'` is needed here.

2021-06-24 15:42 UTC, benarmston commented on builders/flight-job-script-api/package-scripts/flight-job-script-api/postinst
> +${flight_ROOT}/bin/flight service configure --force job-script-api >/dev/null 2>&1
I think `--config '{}'` is needed here.

2021-06-24 15:42 UTC, benarmston commented on builders/flight-login-api/package-scripts/flight-login-api/postinst
> +${flight_ROOT}/bin/flight service configure --force login-api
I think `--config '{}'` is needed here.

2021-06-24 15:42 UTC, benarmston commented on builders/flight-www/package-scripts/flight-www/postinst
> +/opt/flight/bin/flight service configure --force www >/dev/null 2>&1
I think `--config '{}'` is needed here.

2021-06-24 15:42 UTC, benarmston commented on share/config/software/update_web_suite_package_scripts.rb
> +                  "${flight_ROOT}/bin/flight service configure --force #{service} >/dev/null 2>&1"
I think `--config '{}'` is needed here.

2021-06-24 15:42 UTC, benarmston commented
@WilliamMcCumstie what's the reason for the change to the service script permissions?

2021-06-25 09:09 UTC, WilliamMcCumstie commented
The `puma` file permissions is a pre-existing change:

https://github.com/openflighthpc/openflight-omnibus-builder/blob/42bdc7c432b308bdb757ca76585bde62a1125b22/share/config/software/update_puma_scripts.rb#L266

The actual permissions are being changed now due to the scripts being re-rendered

2021-06-25 09:24 UTC, WilliamMcCumstie commented on share/config/software/update_web_suite_package_scripts.rb
> +                  "${flight_ROOT}/bin/flight service configure --force #{service} >/dev/null 2>&1"
https://github.com/openflighthpc/openflight-omnibus-builder/pull/134/commits/13bd21d2b900015f568d025b0411c1030d454b2b

2021-06-25 09:24 UTC, WilliamMcCumstie commented on builders/flight-www/package-scripts/flight-www/postinst
> +/opt/flight/bin/flight service configure --force www >/dev/null 2>&1
https://github.com/openflighthpc/openflight-omnibus-builder/pull/134/commits/13bd21d2b900015f568d025b0411c1030d454b2b

2021-06-25 09:24 UTC, WilliamMcCumstie commented on builders/flight-login-api/package-scripts/flight-login-api/postinst
> +${flight_ROOT}/bin/flight service configure --force login-api
https://github.com/openflighthpc/openflight-omnibus-builder/pull/134/commits/13bd21d2b900015f568d025b0411c1030d454b2b

2021-06-25 09:24 UTC, WilliamMcCumstie commented on builders/flight-job-script-api/package-scripts/flight-job-script-api/postinst
> +${flight_ROOT}/bin/flight service configure --force job-script-api >/dev/null 2>&1
https://github.com/openflighthpc/openflight-omnibus-builder/pull/134/commits/13bd21d2b900015f568d025b0411c1030d454b2b

2021-06-25 09:24 UTC, WilliamMcCumstie commented on builders/flight-file-manager-api/package-scripts/flight-file-manager-api/postinst-configure
> +${flight_ROOT}/bin/flight service configure --force file-manager-api >/dev/null 2>&1
https://github.com/openflighthpc/openflight-omnibus-builder/pull/134/commits/13bd21d2b900015f568d025b0411c1030d454b2b

2021-06-25 09:24 UTC, WilliamMcCumstie commented on builders/flight-file-manager-api/package-scripts/flight-file-manager-api/postinst
> +${flight_ROOT}/bin/flight service configure --force file-manager-api >/dev/null 2>&1
https://github.com/openflighthpc/openflight-omnibus-builder/pull/134/commits/13bd21d2b900015f568d025b0411c1030d454b2b

2021-06-25 09:24 UTC, WilliamMcCumstie commented on builders/flight-desktop-restapi/package-scripts/flight-desktop-restapi/postinst
> +${flight_ROOT}/bin/flight service configure --force desktop-restapi >/dev/null 2>&1
https://github.com/openflighthpc/openflight-omnibus-builder/pull/134/commits/13bd21d2b900015f568d025b0411c1030d454b2b

2021-06-25 09:24 UTC, WilliamMcCumstie commented on builders/flight-console-api/package-scripts/flight-console-api/postinst-configure
> +${flight_ROOT}/bin/flight service configure --force >/dev/null 2>&1
https://github.com/openflighthpc/openflight-omnibus-builder/pull/134/commits/13bd21d2b900015f568d025b0411c1030d454b2b

2021-06-25 09:24 UTC, WilliamMcCumstie commented on builders/flight-console-api/package-scripts/flight-console-api/postinst
> +${flight_ROOT}/bin/flight service configure --force >/dev/null 2>&1
https://github.com/openflighthpc/openflight-omnibus-builder/pull/134/commits/13bd21d2b900015f568d025b0411c1030d454b2b

2021-06-25 16:00 UTC, merged