Rolling PR for flight-scheduler
openflighthpc/openflight-omnibus-builder pull request #49
Opened 2020-09-15 16:29 UTC by WilliamMcCumstie

This PR will be used to track the progress of `flight-scheduler`

2020-10-01 15:52 UTC, benarmston requested changes
@WilliamMcCumstie can you explain why the stderr redirection/reopening is required.  Why would a simple `2> /whatever/path.log` not be sufficient?

2020-10-01 15:52 UTC, benarmston commented on builders/flight-scheduler/opt/flight/etc/service/types/scheduler-controller/start.sh
> +# Wait up to 10ish seconds for falcon to start
We have a new script to get the falcon pid in https://github.com/openflighthpc/flight-scheduler-controller/pull/16.

2020-10-08 12:35 UTC, WilliamMcCumstie commented on builders/flight-scheduler/opt/flight/etc/service/types/scheduler-controller/start.sh
> +  "$log_file" --threaded -n 2 -b "$addr"
Updated to use `falcon-host`

2020-10-08 12:35 UTC, WilliamMcCumstie commented on builders/flight-scheduler/opt/flight/etc/service/types/scheduler-controller/start.sh
> +cd "$flight_ROOT"/opt/scheduler/controller
Appears not

2020-10-08 12:35 UTC, WilliamMcCumstie commented on builders/flight-scheduler/opt/flight/etc/service/types/scheduler-controller/start.sh
> +# Wait up to 10ish seconds for falcon to start
Switched

2020-10-08 12:36 UTC, WilliamMcCumstie commented
> @WilliamMcCumstie can you explain why the stderr redirection/reopening is required. Why would a simple `2> /whatever/path.log` not be sufficient?

Updated to use `copytruncate` instead of reopening the logs

2020-10-12 10:10 UTC, benarmston commented
LGTM.

2020-10-12 10:10 UTC, merged