Rolling PR for action-api azure and ipmi scripts
openflighthpc/openflight-omnibus-builder pull request #63
Opened 2020-11-11 14:29 UTC by WilliamMcCumstie

RONSEAL

2020-11-11 16:26 UTC, benarmston commented on builders/flight-action-api-estate/config/software/flight-action-api-estate.rb
> +    end
So this only brings in the helpers for estate actions.  They won't be present if `flight-action-api-power` is installed.  Which is fine as only estate actions require them at the moment.

If other namespaces do require them, we will need to reconsider this as we don't want multiple RPMs owning the same file.

2020-11-11 16:32 UTC, benarmston commented on builders/flight-action-api/opt/flight/etc/service/env/action-api
> +PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
IIUC you've added this because the azure package you installed places its executables at `/usr/local/bin`, and `flight-service` doesn't add that directory to the path.

There are a few options available to address that

1. Hardcode the entire path in the env file (what you've done here).
2. Modify the path in the env file, e.g., `PATH=/usr/local/sbin:/usr/local/bin:$PATH`.
3. Modify flight service to add those paths by default.
4. Use the full path in the scripts.

I'd prefer (2) over (1) if possible.  I might also prefer (3) or (4) to having the entire path hardcoded here.  Did you attempt (2)?

2020-11-11 16:57 UTC, WilliamMcCumstie commented on builders/flight-action-api/opt/flight/etc/service/env/action-api
> +PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
Just attempted option 2 and it didn't work. Flight service uses a custom env parser which does not support string interpolation:
https://github.com/openflighthpc/flight-service/blob/master/lib/service/env_parser.rb

I'm not a fan of option 4 for following reasons:

* It assumes `pip3` installs the binary consistently across all OSes,
* I'm not sure what will happen if a system tried to use `pip` instead, and
* It makes it trickier to sub out the version of `python`/`az` if required at some future date.

Option 2 and 3 sound like good ideas, I'm slightly more partial to option 2. However implementing them going to need a release of `flight-service`.

Are there any particular issues you are concerned about with the current implementation (option 1)? In effect `flight-service` forces the PATH to be a static value `/usr/sbin:/usr/bin:/sbin:/bin`. I don't see to much risk involved hard overriding a static value with another static value.

Very least it seems like a decent stopgap measure until `flight-service` catches up.

2020-11-11 16:59 UTC, WilliamMcCumstie commented on builders/flight-action-api/opt/flight/etc/service/env/action-api
> +PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
Possible flag the file as a `config_file` so it can be edited if need be

2020-11-11 17:05 UTC, WilliamMcCumstie commented on builders/flight-action-api-estate/config/software/flight-action-api-estate.rb
> +    end
I was contemplating this issue but in the end decided it is a bit moot. It easy enough to add a dependency between `flight-action-api-estate` and `flight-actio-api-power` if the files need to be shared. Or possible package the the helper scripts independently.

Absolutely agree it is critical only one package owns each file. That is why they are added on a script basis as opposed to the entire `helpers` directory.

FYI the `helpers` directory is special cased by omitting the `metadata.yaml` and not by name. It would be a fairly trivial change to rename it `estate-helpers` if you are concerned about ownership.

2020-11-11 17:09 UTC, benarmston commented on builders/flight-action-api/opt/flight/etc/service/env/action-api
> +PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
My concern is if the path set by `flight-service` changes and this file is not updated to match, we could end up with inconsistent and difficult to debug behaviour.

Like everything else, there is a limit to how much effort we should put into avoiding *potential* issues.  So as (2) doesn't work, I'd agree that this is a decent stopgap measure.  We should consider extending the `flight-service` env parser to support option (2).

2020-11-11 17:14 UTC, benarmston commented on builders/flight-action-api-estate/config/software/flight-action-api-estate.rb
> +    end
I'm not terribly concerned with it at the moment.  At some point we'll need to address this.  We'll have a better idea of how when that's the case.  Perhaps, all helpers ship with `flight-action-api` itself?

For now its fine.  I was just thinking out loud.

2020-11-11 17:15 UTC, WilliamMcCumstie commented on builders/flight-action-api/opt/flight/etc/service/env/action-api
> +PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
:+1:

2020-11-12 11:43 UTC, WilliamMcCumstie commented on builders/flight-action-api-estate/config/software/flight-action-api-estate.rb
> +    end
:+1:

2020-11-26 11:09 UTC, benarmston commented on builders/flight-action-api/opt/flight/etc/service/env/action-api
> +PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
I've created a trello card to track the possible enhancement to the `flight-service` env parser.

2020-11-26 11:16 UTC, benarmston requested changes

2020-11-26 11:16 UTC, benarmston commented on builders/flight-ipmi/config/projects/flight-ipmi.rb
> +build_iteration 2
This should be `build_iteration 1`

2021-02-05 10:19 UTC, benarmston commented
Rebased on `master`.

2021-02-05 10:19 UTC, merged

2021-02-05 10:20 UTC, benarmston commented
I clicked too many buttons and accidentally merged this PR.  I'll open a new PR to address the changes required.