Rolling PR for flight-job 1.2.X
openflighthpc/openflight-omnibus-builder pull request #89
Opened 2021-03-04 11:00 UTC by WilliamMcCumstie

RONSEAL

2021-03-22 17:21 UTC, benarmston requested changes
This looks close to being ready to go.  I've made some changes to the `howto` and added a couple of items for you to look at.  There is also the script templates that need some minor work as mentioned in real life.

2021-03-22 17:21 UTC, benarmston commented on builders/flight-job/opt/flight/libexec/job/flight-slurm/monitor.sh
> +PATH=/opt/flight/opt/slurm/bin:$PATH
How did you determine that this was the correct order?  The file `/opt/flight/etc/profile.d/90-slurm.sh` does it the other way around.  We ought to be consistent between the two.

2021-03-22 17:21 UTC, benarmston commented on builders/flight-job/opt/flight/libexec/job/flight-slurm/submit.sh
> +PATH=/opt/flight/opt/slurm/bin:$PATH
Ditto.

2021-03-23 14:18 UTC, WilliamMcCumstie commented on builders/flight-job/opt/flight/libexec/job/flight-slurm/submit.sh
> +PATH=/opt/flight/opt/slurm/bin:$PATH
https://github.com/openflighthpc/openflight-omnibus-builder/pull/89/commits/7b9ba14e889245dcc5d63b6b04ef86133935e4a7

2021-03-23 14:18 UTC, WilliamMcCumstie commented on builders/flight-job/opt/flight/libexec/job/flight-slurm/monitor.sh
> +PATH=/opt/flight/opt/slurm/bin:$PATH
https://github.com/openflighthpc/openflight-omnibus-builder/pull/89/commits/7b9ba14e889245dcc5d63b6b04ef86133935e4a7

2021-03-23 18:18 UTC, merged