Rolling PR for flight-service-1.3.X
openflighthpc/openflight-omnibus-builder pull request #91
Opened 2021-03-18 18:16 UTC by WilliamMcCumstie

This work will likely supersede the previous `flight-configure` work.

2021-04-19 13:16 UTC, benarmston requested changes
There is already a mechanism for starting enabled services.  The cron job needs to be removed.

2021-04-19 13:16 UTC, benarmston commented on builders/flight-service/package-scripts/flight-service/postinst
> +chmod u+x /opt/flight/etc/cron/reboot/start-enabled-services
We don't need this.  The packages `flight-plugin-{system,manual}-systemd-service` exist to fix this issue.

2021-04-19 13:16 UTC, benarmston commented on builders/flight-service/package-scripts/flight-service/postrm
> +rm /opt/flight/etc/cron/reboot/start-enabled-services
We don't need this either.

2021-04-19 16:34 UTC, WilliamMcCumstie commented
Removed

2021-04-29 09:56 UTC, benarmston commented
LGTM

2021-04-29 09:56 UTC, merged